start: instruction+

instruction: stroke | brush
stroke: STROKECOMMAND coordinate coordinate [curve] [wavy] -> stroke
brush: BRUSHCOMMAND (brushvalue)+  -> brush
coordinate: value value  -> coordinate
brushvalue: hue | sat | bright | alpha | thick | rough -> brushvalue

// brush properties
hue: "h" value -> hue
sat: "s" value -> sat
bright: "b" value -> bright
alpha: "a" value -> alpha
thick: "t" value -> thick
rough: "r" value -> rough

// path properties
curve: "c" value -> curve
wavy:  "w" value -> wavy

STROKECOMMAND: "stroke"
BRUSHCOMMAND: "brush"
uniform: "u" -> uniform
normal: "n" -> normal
value: NUMBER | ((uniform | normal) NUMBER ":" NUMBER)

%import common.FLOAT -> NUMBER
%import common.WS
%ignore WS